# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_and_icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='logo/%y/%m/%d')),
                ('icons', models.ImageField(blank=True, upload_to='icons/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Main_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='main/%y/%m/%d')),
            ],
        ),
    ]
