# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo_and_icons',
            name='icons',
            field=models.ImageField(blank=True, upload_to='upload_files/icons/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='logo_and_icons',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload_files/logo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='main_pic',
            name='main_image',
            field=models.ImageField(upload_to='upload_files/main/%y/%m/%d'),
        ),
    ]
